# Generated by Django 3.1.5 on 2021-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20210113_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(default='', max_length=255),
        ),
    ]
